Mango.Web/Controllers/AuthController.cs
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Mango.Web.Utilities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Mango.Web.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ITokenProvider _tokenProvider;

    public AuthController(IAuthService authService, ITokenProvider tokenProvider)
    {
        _authService = authService;
        _tokenProvider = tokenProvider;
    }

    [HttpGet]
    public IActionResult Login()
    {
        LoginRequestDto loginRequestDto = new();
        return View(loginRequestDto);
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDto dto)
    {
        var result = await _authService.LoginAsync(dto);

        if (result is not null && result.IsSuccess)
        {
            LoginResponseDto response = JsonConvert.DeserializeObject<LoginResponseDto>(result.Result.ToString());

            await SignInUser(response);
            _tokenProvider.SetToken(response.Token);
            return RedirectToAction(nameof(Index), "Home");
        }

        TempData["error"] = result.Message;
        return View(dto);
    }

    [HttpGet]
    public IActionResult Register()
    {
        var RoleList = new List<SelectListItem>
        {
            new() { Text = SD.RoleAdmin, Value = SD.RoleAdmin },
            new() { Text = SD.RoleCustomer, Value = SD.RoleCustomer }
        };

        ViewBag.RoleList = RoleList;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegistrationRequestDto dto)
    {
        var result = await _authService.RegisterAsync(dto);

        if (result is not null || result.IsSuccess)
        {
            if (string.IsNullOrEmpty(dto.Role))
            {
                dto.Role = SD.RoleCustomer;
            }

            var assignResponse = await _authService.AssignRoleAsync(dto);

            if (assignResponse is not null && assignResponse.IsSuccess)
            {
                TempData["Success"] = "Registration successful.";
                return RedirectToAction(nameof(Login));
            }
        }
        else
        {
            TempData["error"] = result.Message;
        }

        var RoleList = new List<SelectListItem>
        {
            new() { Text = SD.RoleAdmin, Value = SD.RoleAdmin },
            new() { Text = SD.RoleCustomer, Value = SD.RoleCustomer }
        };

        ViewBag.RoleList = RoleList;
        return View(dto);
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();
        return RedirectToAction(nameof(Login));
    }

    private async Task SignInUser(LoginResponseDto dto)
    {
        var handler = new JwtSecurityTokenHandler();
        var token =  handler.ReadJwtToken(dto.Token);
        var claims = new List<Claim>();
        claims.Add(new Claim(JwtRegisteredClaimNames.Email,
            token.Claims.FirstOrDefault(c => c.Type == JwtRegisteredClaimNames.Email).Value));
        claims.Add(new Claim(JwtRegisteredClaimNames.Name,
            token.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));
        claims.Add(new Claim(JwtRegisteredClaimNames.Sub,
            token.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
        
        claims.Add(new Claim(ClaimTypes.Name,
            token.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
        claims.Add(new Claim(ClaimTypes.Role, token.Claims.FirstOrDefault(u => u.Type == "role").Value));
        
        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
        identity.AddClaims(claims);

        var principal = new ClaimsPrincipal(identity);
        await HttpContext.SignInAsync(principal);
    }
}

Mango.Web/Controllers/CartController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Mango.Web.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;

namespace Mango.Web.Controllers;

public class CartController : Controller
{
    private readonly ICartService _cartService;
    private readonly IOrderService _orderService;

    public CartController(ICartService cartService, IOrderService orderService)
    {
        ArgumentNullException.ThrowIfNull(cartService);
        ArgumentNullException.ThrowIfNull(orderService);

        _cartService = cartService;
        _orderService = orderService;
    }

    [Authorize]
    public async Task<IActionResult> CartIndex()
    {
        return View(await LoadCartDtoBasedOnLoggedInUser());
    }

    [Authorize]
    public async Task<IActionResult> Checkout()
    {
        return View(await LoadCartDtoBasedOnLoggedInUser());
    }

    [HttpPost]
    [ActionName("Checkout")]
    public async Task<IActionResult> Checkout(CartDto cartDto)
    {
        CartDto cart = await LoadCartDtoBasedOnLoggedInUser();
        cart.CartHeader.Phone = cartDto.CartHeader.Phone;
        cart.CartHeader.Email = cartDto.CartHeader.Email;
        cart.CartHeader.Name = cartDto.CartHeader.Name;

        var response = await _orderService.CreateOrderAsync(cart);

        if (response == null || !response.IsSuccess)
        {
            TempData["error"] = "Order creation failed";
            return View(cart);
        }

        var orderHeaderDto = JsonConvert.DeserializeObject<OrderHeaderDto>(Convert.ToString(response.Result));

        var domain = $"{Request.Scheme}://{Request.Host.Value}";
        var paymentRequestDto = new PaymentRequestDto
        {
            OrderHeader = orderHeaderDto,
            OnCancelUrl = $"{domain}/cart/Checkout",
            OnSuccessUrl = $"{domain}/cart/Confirmation?orderId={orderHeaderDto.OrderHeaderId}"
        };
        var paymentResponse = await _orderService.CreateSessionAsync(paymentRequestDto);

        if (paymentResponse == null || !paymentResponse.IsSuccess)
        {
            TempData["error"] = "Payment session creation failed";
            return View(cart);
        }

        var paymentResponseDto =
            JsonConvert.DeserializeObject<PaymentRequestDto>(Convert.ToString(paymentResponse.Result));
        Response.Headers.Append("Location", paymentResponseDto.SessionUrl);

        return new StatusCodeResult(303);
    }

    public async Task<IActionResult> Confirmation(int orderId)
    {
        var response = await _orderService.ValidateSessionAsync(orderId);
        if (response == null || !response.IsSuccess)
        {
            // TODO: redirect to error page
            return View(orderId);
        }

        var orderHeader = JsonConvert.DeserializeObject<OrderHeaderDto>(Convert.ToString(response.Result));
        if (orderHeader != null && orderHeader.Status == SD.Status.Approved)
        {
            return View(orderId);
        }

        // TODO: redirect to error page
        return View(orderId);
    }

    public async Task<IActionResult> Remove(int cartDetailsId)
    {
        var response = await _cartService.RemoveFromCartAsync(cartDetailsId);
        if (response != null && response.IsSuccess)
        {
            TempData["success"] = "Cart updated successfully";
            return RedirectToAction(nameof(CartIndex));
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ApplyCoupon(string userId, string couponCode)
    {
        var response = await _cartService.ApplyCouponAsync(userId, couponCode);
        if (response != null && response.IsSuccess)
        {
            TempData["success"] = "Cart updated successfully";
            return RedirectToAction(nameof(CartIndex));
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> RemoveCoupon(string userId)
    {
        var response = await _cartService.RemoveCouponAsync(userId);
        if (response != null && response.IsSuccess)
        {
            TempData["success"] = "Cart updated successfully";
            return RedirectToAction(nameof(CartIndex));
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> EmailCart(CartDto cartDto)
    {
        if (cartDto.CartDetails == null || !cartDto.CartDetails.Any())
        {
            TempData["error"] = "Cart is empty";
            return RedirectToAction(nameof(CartIndex));
        }

        var cartDetails = cartDto.CartDetails.ToList();
        foreach (var dto in cartDetails)
        {
            if (dto.Product?.ImageURL == null)
            {
                dto.Product.ImageURL = string.Empty;
            }
        }

        var email = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Email)?.FirstOrDefault()?.Value;
        cartDto.CartHeader.Email = email;

        var response = await _cartService.EmailCartAsync(cartDto);
        if (response != null && response.IsSuccess)
        {
            TempData["success"] = "Email will be processed and sent shortly";
            return RedirectToAction(nameof(CartIndex));
        }

        TempData["error"] = "Email processing failed";
        return RedirectToAction(nameof(CartIndex));
    }

    private async Task<CartDto> LoadCartDtoBasedOnLoggedInUser()
    {
        var userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
        var response = await _cartService.GetCartByUserIdAsync(userId);
        if (response != null && response.IsSuccess)
        {
            CartDto cartDto = JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result));
            return cartDto;
        }

        return new CartDto();
    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers;

public class CouponController : Controller
{
    private readonly ICouponService _couponService;
    public CouponController(ICouponService couponService)
    {
        _couponService = couponService;
    }
    
    public async Task<IActionResult> CouponIndex()
    {
        
        Console.WriteLine("Requesting coupons from CouponService...");
        List<CouponDto>? coupons = new();
        var response = await _couponService.GetAllCouponsAsync();
        if (response != null && response.IsSuccess)
        {
            Console.WriteLine("Received coupons from CouponService.");
            coupons = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result) ?? string.Empty);
        }
        else
        {
            TempData["Error"] = response?.Message;
        }

        Console.WriteLine("Rendering CouponIndex view...");
        return View(coupons);
    }

    public IActionResult CouponCreate()
    {
        Console.WriteLine("Rendering CreateCoupon view...");
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> CouponCreate(CouponDto model)
    {
        Console.WriteLine("Saving CreateCoupon model...");
        if (ModelState.IsValid)
        {
            Console.WriteLine("Model is valid. Saving model...");
            var response = await _couponService.CreateCouponAsync(model);
            
            if (response != null && response.IsSuccess)
            {
                Console.WriteLine("Model saved successfully.");
                TempData["Success"] = "Coupon created successfully.";
                return RedirectToAction("CouponIndex");
            }
            else
            {
                TempData["Error"] = response?.Message;
            }
        }
        return View(model);
    }

    public async Task<IActionResult> CouponView(int couponId)
    {
        Console.WriteLine("Viewing coupon with Id " + couponId);
        var response = await _couponService.GetCouponByIdAsync(couponId);
        if (response != null && response.IsSuccess)
        {
            Console.WriteLine("Rendering CouponView view...");
            var model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result) ?? string.Empty);
            return View(model);
        }
        else
        {
            TempData["Error"] = response?.Message;
        }

        return NotFound();
    }
    
    public async Task<IActionResult> CouponDelete(int couponId)
    {
        Console.WriteLine("Deleting coupon...");
        var response = await _couponService.DeleteCouponAsync(couponId);
        if (response != null && response.IsSuccess)
        {
            Console.WriteLine("Coupon deleted successfully.");
            TempData["Success"] = "Coupon deleted successfully.";
            return RedirectToAction("CouponIndex");
        }
        else
        {
            TempData["Error"] = response?.Message;
        }
        return RedirectToAction("CouponIndex");
    }
}

Mango.Web/Views/Shared/_Layout.cshtml
@using Mango.Web.Utilities;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.IsInRole(SD.RoleAdmin))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Contents Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Product</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                            </ul>
                        </li>
                    }
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="CartIndex">
                            &nbsp; <i class="bi bi-cart"></i> &nbsp;
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
        <partial name="_Notifications"/>
    </main>
</div>

<footer class="footer text-muted">
    <div class="text-center">
        Made by Ashmit <i class="bi bi-person-heart"></i>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mango.Web/Views/Shared/_Notifications.cshtml
@if(TempData["Error"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}
@if(TempData["Success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
    </script>
}